### ISSUE TITLE
Depth First Search

### ISSUE THREAD

**Issue by ChrisPsa** [HPAC/linnea#15]

**Comment by ChrisPsa** [comment]
List of functions to be changed to generators:

- [ ] `linnea.derivation.graph.utils`

**Comment by ChrisPsa** [comment]
`derivation.graph.base.derivation.TR_factorizations` is not straightforward due to `found_symbol_occurrence`.

**Comment by ChrisPsa** [comment]
Does it make sense for `TR_matrix_chain` and `TR_addition` to return lists?

**Comment by henrik227** [comment]
> Does it make sense for `TR_matrix_chain` and `TR_addition` to return lists?

I'm not sure. Those functions are for the constructive strategy, and right now they always return at most one new Equations object. On the other hand, it used to be a convention that the TR_* functions return lists. In the future, the convention would be that they are generators.

**Comment by ChrisPsa** [comment]
We need to check what other functions have to change for Linnea to function properly with the generators.

**Comment by henrik227** [comment]
The class hierarchy needs to be changed to allow for all combinations of contructive/exhaustive strategy and DFS/BFS.

By now, the `derivation` method of DerivationGraph in `derivation.graph.contructive` and `derivation.graph.exhaustive` is almost exactly the same. They should be made the same and moved to a common superclass, probably `DerivationGraphBase` in `derivation.graph.base.derivation`. Same for the DS_kernels method. There is one difference, but I’m not sure if there is a good reason for this difference. We need to investigate this.
