### ISSUE TITLE
Running example script fails

### ISSUE THREAD

**Issue by julihoh** [HPAC/linnea#2]
Running the example script from examples/run_linnea.py fails with the following exception:
```
Traceback (most recent call last):
  File "/Users/user/Code/linnea/examples/run_linnea.py", line 4, in <module>
    import linnea.config
  File "/Users/user/Code/linnea/linnea/config.py", line 247, in <module>
    load_config()
  File "/Users/user/Code/linnea/linnea/config.py", line 237, in load_config
    set_output_path(value)
  File "/Users/user/Code/linnea/linnea/config.py", line 157, in set_output_path
    raise DirectoryDoesNotExist(output_path)
linnea.config.DirectoryDoesNotExist: /Users/user/path/to/output
```
Note that examples/config.json sets the output path to "~/path/to/output" which might not necessarily exist. Not also however, that the output path option would be overridden in the code to be ".", but the example crashes before it comes to that.
From reading the README.md it sounds like since options from a config.json can be overridden via `linnea.config.set_X` that a non existing directory should not crash the example.

**Comment by henrik227** [comment]
This is intentional. The idea was to force the user to think about where to write the output instead of just writing it somewhere without the user expecting it. Do you think using "." is more reasonable and point that out in the readme?

**Comment by julihoh** [comment]
I think it is not unreasonable to ask the user to explicitly define an output path, but since the script at examples/run_linnea.py already specifies the output path to be "." [in the code](https://github.com/HPAC/linnea/blob/master/examples/run_linnea.py#L6), seemingly overriding what is already defined in [here](https://github.com/HPAC/linnea/blob/master/examples/config.json#L2). I think it is reasonable to expect the user the read the example code before running it.

So the change I would suggest is either:
* make the script not fail, if the output path set in the config.json is overridden by the script

-or-
* remove the configuration from the example script and explicitly mention the configuration file in the example directory

But this is just my 2 cents. If you think the current behavior is good as is, I wouldn't make too big of a fuzz about it ;)

**Comment by henrik227** [comment]
I decided to change example/config.json. In addition, I added a paragraph about the output in the readme.
