### ISSUE TITLE
OSError (File Not Found)

### ISSUE THREAD

**Issue by as641651** [HPAC/linnea#24]
https://github.com/HPAC/linnea/blob/8d51d68d44f058784aeef98682688ef9b95e2165/examples/run_linnea.py#L22

I get the following error when I call `graph.write_output` with `experiment_code=True`. 

```code
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1465, in _get
    return self.loader.get_data(path)
OSError: [Errno 0] Error: 'linnea/code_generation/experiments/templates/Cpp/CMakeLists.txt'
````

**Comment by henrik227** [comment]
Fixed.
