### ISSUE TITLE
Dimension mismatch 

### ISSUE THREAD

**Issue by as641651** [HPAC/linnea#27]
I'm getting dimension mismatch for this example while executing the runner script. 

```
        A = Matrix("A", (m, n))

        B = Matrix("B", (n, k))

        C = Matrix("C", (k, l))

        D = Matrix("D", (k, l))

        Y = Matrix("Y", (m, l))

        # Y = AB(C+ D)
        
        self.eqns = Equations(Equal(Y,Plus(Times(A,B,C),Times(A,B,D))))
```

**Comment by henrik227** [comment]
Could you please post the error message, and the version (commit) of Linnea you are using?

What are the values of m, n, k, and l? Could they be 1?

**Comment by as641651** [comment]
It occurs for any m,n,k,l when they are all different. (say 10,20,1244,1151)

snapshot of error:

```
ERROR: LoadError: DimensionMismatch("A has size (10,1244), B has size (1244,1151), C has size (10, 13)")
Stacktrace:
 [1] gemm!(::Char, ::Char, ::Float64, ::Array{Float64,2}, ::Array{Float64,2}, ::Float64, ::Array{Float64,2}) at /julia/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/blas.jl:1117
 [2] algorithm1(::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}) at /home/user/measurements/expressions/suit/logs/Example002/Example002_D30/SD0_Example002_D30/expressions/sample_10_20_1244_1151/Julia/experiments/algorithm1.jl:23
 [3] measure(::Int64, ::Function, ::Array{Float64,2}, ::Vararg{Array{Float64,2},N} where N) at /root/.julia/packages/MatrixGenerator/QBiUe/src/benchmarker/Benchmarker.jl:70
 [4] macro expansion at ./logging.jl:308 [inlined]
 [5] main() at /home/user/measurements/expressions/suit/logs/Example002/Example002_D30/SD0_Example002_D30/results_FE_rubik_4t_0d_20r/sample_10_20_1244_1151/17runner.jl:23
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] exec_options(::Base.JLOptions) at ./client.jl:229
 [11] _start() at ./client.jl:421
```

**Comment by henrik227** [comment]
I still need more information to help you with this. It looks like a matrix of size 10 x 13 is used in the experiments, even though it should be of size 10 x 1151. How do you generate the input operands?

**Comment by as641651** [comment]
The dimensions shown in the error are sizes of intermidiate operands in the
generated code. I think you can reproduce this error just with that example.

**Comment by henrik227** [comment]
> The dimensions shown in the error are sizes of intermidiate operands in the generated code. I think you can reproduce this error just with that example.

I just tried it, and I can't reproduce the error. According to the error message you posted, the problem is in line 23 of algorithm1. For me, with your sizes, those are lines 20 to 23:

```julia
    # tmp1: ml3, full, tmp2: ml4, full
    ml5 = Array{Float64}(undef, 10, 1151)
    # tmp4 = (tmp2 tmp1)
    gemm!('N', 'N', 1.0, ml4, ml3, 0.0, ml5)
```

Operand `C` in the error message is `ml5` here. So yes, it shouldn't be related to the generation of operands. Since I can't reproduce the error, I suspect that you either somehow mixed up some files, or you are generating algorithms for multiple expressions within the same script, and that causes weird side effects. In case you are generating algorithms for multiple expressions within the same script, are you calling `config.clear_all()` in between?

**Comment by as641651** [comment]
Yes, I do generate multiple expressions within the same script. I do call config.clear_all()

```python
    for i, eqns in enumerate(eqns_list):
        from linnea.derivation.graph.derivation import DerivationGraph
        out_dir = os.path.join(expressions_folder, "SD"+str(i)+"_"+expression_id,"expressions")
        linnea.config.set_output_code_path(out_dir)
        linnea.config.set_generate_graph(True)
        linnea.config.init()
        for id,expr in eqns.items():
            generate_code(id,expr,out_dir)

def generate_code(id, equations,out_dir):
    linnea.config.clear_all()
    graph = DerivationGraph(equations)
    graph.derivation(time_limit=TIME_LIMIT,
                     merging=True,
                     dead_ends=True,
                     pruning_factor=1.5)

    algorithms = graph.write_output(code=True,
                                   derivation=True,
                                   output_name=id,
                                   k_best=False,
                                   subdir_name_experiments = "experiments",
                                   experiment_code=True,
                                   algorithms_limit=100,
                                   graph=True,
                                   no_duplicates=True)
```

**Comment by henrik227** [comment]
Is it possible that in the different expressions, you are using operands with the same name, but different sizes?

**Comment by as641651** [comment]
yes. But they are different equation instances.

```python
class Example002():
    def __init__(self,m,n,k,l):

        # TAGS

        A = Matrix("A", (m, n))

        B = Matrix("B", (n, k))

        C = Matrix("C", (k, l))

        D = Matrix("D", (k, l))

        Y = Matrix("Y", (m, l))

        # Y = AB(C+ D)

        self.eqns = Equations(Equal(Y, Times(A, B, Plus(C,D))))
```

**Comment by as641651** [comment]
So it seems to work when I use unique operand names. This is my temporary fix..

```python
        arg_tag = str(m)+"_"+str(n)+"_"+str(k)+"_"+str(l)

        A = Matrix("A_"+arg_tag, (m, n))

        B = Matrix("B_"+arg_tag, (n, k))

        C = Matrix("C_"+arg_tag, (k, l))

        D = Matrix("D_"+arg_tag, (k, l))

        Y = Matrix("Y_"+arg_tag, (m, l))
```

**Comment by henrik227** [comment]
I've seen similar behavior before, and it seems to originate in MatchPy. I have some ideas for how this could be fixed, but I currently don't have time to look into it. Until it's fixed, using unique operand names is the best solution I can offer you.

**Comment by henrik227** [comment]
It looks like the problem was easier to fix than I thought. Could you please test if the fix solves this problem for you when you are again using the same operand names? You need to use the `reset_caching` branch of both Linnea and MatchPy.

**Comment by as641651** [comment]
yea, it's working now. thanks
