### ISSUE TITLE
Use Linnea frontend to emit IR

### ISSUE THREAD

**Issue by chelini** [HPAC/linnea#30]
Dear All,
I would be interested in using the Linnea frontend to parse a specific expression and emit intermediate representation (compiler IR). Can I use the class Equation to do that? (https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/algebra/equations.py#L35) I miss some information regarding the type of the expression (i.e., mul or add) as well as the type of its operand. But I may be wrong. Did I miss something?
Thanks a lot

**Comment by hbarthels** [comment]
Hi Lorenzo,
I think it should be possible to use the `Equations` class, but the information that you are looking for is not stored at this level. The `Equations` class is just a thin wrapper to hold multiple expressions/equations. You can access those expressions either individually (`equations[i]`), or loop over them (`for eqn in equations`). In both cases, what you get are expression trees (defined [here](https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/algebra/expression.py)) that should contain the information you need. To extract all of that, you probably need to traverse those trees. To get an idea for how to do that, you could either take a look at a function like this
https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/algebra/transformations.py#L389 or those functions:
https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/algebra/expression.py#L499-L512
