### ISSUE TITLE
Why generate duplicate code?

### ISSUE THREAD

**Issue by as641651** [HPAC/linnea#31]
Why not default no_duplicates=True? or Is there any reason to generate duplicate code?

https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/algorithm_generation/graph/base/equations.py#L208

**Comment by hbarthels** [comment]
Because removing those duplicates is somewhat expensive, and they were usually not a problem for what I was doing.
